//! Fleet-wide NixOS build revision status viewer.
//!
//! This module implements a read-only CLI tool that displays NixOS system build
//! revisions across a fleet of hosts. It can operate in two modes:
//!
//! 1. **Local-only mode**: Shows revision information for the current host by
//!    reading from standard NixOS system state paths.
//!
//! 2. **Fleet mode**: Connects to ZooKeeper to display revision information for
//!    all hosts in the fleet that have published their state.
//!
//! ## Architecture
//!
//! The CLI reads three system states for each host:
//! - **Current**: The currently running system (`/run/current-system`)
//! - **Booted**: The system that was booted (`/run/booted-system`)
//! - **Next boot**: The system that will boot next (`/nix/var/nix/profiles/system`)
//!
//! In fleet mode, the CLI fetches equivalent data from ZooKeeper znodes under
//! a configured namespace (default: `/nixos/versions/{hostname}/{state}`).
//!
//! ## Configuration
//!
//! Configuration is loaded from a TOML file located at:
//! - `$OGYGIA_CONFIG` (environment override)
//! - `{system}/sw/share/ogygia/config.toml` (generated by NixOS module)
//!
//! ## Note on Write Side
//!
//! This module only **reads** from ZooKeeper. A separate publisher daemon
//! (not included here) is responsible for writing host state to ZooKeeper.
//!
//! ## Module Organization
//!
//! - `state`: State gathering logic (filesystem, ZooKeeper, config loading)
//! - `display`: Rendering and formatting logic (tables, truncation, trimming)
//! - `tests`: Unit tests for both state and display modules

mod display;
mod state;

#[cfg(test)]
mod tests;

use anyhow::Result;
use display::print_host_table;
use state::HostMatcher;
use state::collect_local_state;
use state::detect_hostname;
use state::fetch_zookeeper_state;
use state::load_cli_config;
use tracing::info;
use tracing::warn;

/// Main entry point for the status command.
///
/// This function orchestrates the status display by:
/// 1. Loading configuration (if available)
/// 2. Detecting the local hostname
/// 3. Collecting local system state
/// 4. Optionally fetching fleet state from ZooKeeper
/// 5. Rendering the status table
///
/// If ZooKeeper is not configured or connection fails, gracefully falls back
/// to displaying only local host data.
pub fn show_status() -> Result<()> {
    let cli_config = load_cli_config()?;
    let domain_suffix = cli_config
        .as_ref()
        .and_then(|cfg| cfg.domain_suffix.as_deref());

    let host_name = detect_hostname();
    let host_matcher = HostMatcher::new(&host_name);
    let local_state = collect_local_state(host_name);

    match cli_config.as_ref() {
        Some(cli_config) => {
            if let Some(zookeeper) = cli_config.zookeeper.as_ref() {
                info!(
                    namespace = %zookeeper.namespace,
                    config = %cli_config.path.display(),
                    "ZooKeeper fleet state"
                );

                match fetch_zookeeper_state(zookeeper, Some(&host_matcher)) {
                    Ok(remote_states) => {
                        // Combine local and remote states
                        let mut all_states = vec![local_state];
                        all_states.extend(remote_states);

                        if all_states.len() == 1 {
                            info!("only the local host is currently registered in ZooKeeper");
                        }

                        print_host_table(&all_states, domain_suffix);
                    }
                    Err(error) => {
                        warn!(
                            config = %cli_config.path.display(),
                            %error,
                            "failed to read ZooKeeper, showing local data only"
                        );
                        print_host_table(&[local_state], domain_suffix);
                    }
                }
            } else {
                info!(
                    config = %cli_config.path.display(),
                    "ZooKeeper settings not found, showing local data only"
                );
                print_host_table(&[local_state], domain_suffix);
            }
        }
        None => {
            info!("config not found, showing local data only");
            print_host_table(&[local_state], domain_suffix);
        }
    }

    Ok(())
}
