//! Fleet-wide NixOS build revision status viewer.
//!
//! This module implements a read-only CLI tool that displays NixOS system build
//! revisions across a fleet of hosts. It can operate in two modes:
//!
//! 1. **Local-only mode**: Shows revision information for the current host by
//!    reading from standard NixOS system state paths.
//!
//! 2. **Fleet mode**: Connects to etcd to display
//!    revision information for all hosts in the fleet that have published their state.
//!
//! ## Architecture
//!
//! The CLI reads three system states for each host:
//! - **Current**: The currently running system (`/run/current-system`)
//! - **Booted**: The system that was booted (`/run/booted-system`)
//! - **Next boot**: The system that will boot next (`/nix/var/nix/profiles/system`)
//!
//! In fleet mode, the CLI fetches equivalent data from etcd keys under
//! a configured namespace (default: `/nixos/versions/{hostname}/{state}`).
//!
//! ## Configuration
//!
//! Configuration is loaded from a TOML file located at:
//! - `$OGYGIA_CONFIG` (environment override)
//! - `{system}/sw/share/ogygia/config.toml` (generated by NixOS module)
//!
//! ## Note on Write Side
//!
//! This module only **reads** from etcd. A separate publisher daemon
//! (not included here) is responsible for writing host state.
//!
//! ## Module Organization
//!
//! - `state`: State gathering logic (filesystem, etcd, config loading)
//! - `display`: Rendering and formatting logic (tables, truncation, trimming)
//! - `tests`: Unit tests for both state and display modules

mod display;
mod state;

#[cfg(test)]
mod tests;

use anyhow::Result;
use display::print_host_table;
use state::HostMatcher;
use state::collect_local_state;
use state::detect_hostname;
use state::fetch_etcd_state;
use state::load_cli_config;
use tracing::info;
use tracing::warn;

/// Main entry point for the status command.
///
/// This function orchestrates the status display by:
/// 1. Loading configuration (if available)
/// 2. Detecting the local hostname
/// 3. Collecting local system state
/// 4. Optionally fetching fleet state from etcd
/// 5. Rendering the status table
///
/// If no backend is configured or connection fails, gracefully falls back
/// to displaying only local host data.
pub fn show_status() -> Result<()> {
    let cli_config = load_cli_config()?;
    let domain_suffix = cli_config
        .as_ref()
        .and_then(|cfg| cfg.domain_suffix.as_deref());

    let host_name = detect_hostname();
    let host_matcher = HostMatcher::new(&host_name);
    let local_state = collect_local_state(host_name);

    match cli_config.as_ref() {
        Some(cli_config) => {
            if let Some(etcd) = cli_config.etcd.as_ref() {
                info!(
                    namespace = %etcd.namespace,
                    config = %cli_config.path.display(),
                    "etcd fleet state"
                );

                // Create tokio runtime for async etcd operations
                let rt = tokio::runtime::Runtime::new()?;
                match rt.block_on(fetch_etcd_state(etcd, Some(&host_matcher))) {
                    Ok(remote_states) => {
                        // Combine local and remote states
                        let mut all_states = vec![local_state];
                        all_states.extend(remote_states);

                        if all_states.len() == 1 {
                            info!("only the local host is currently registered in etcd");
                        }

                        print_host_table(&all_states, domain_suffix);
                    }
                    Err(error) => {
                        warn!(
                            config = %cli_config.path.display(),
                            %error,
                            "failed to read etcd, showing local data only"
                        );
                        print_host_table(&[local_state], domain_suffix);
                    }
                }
            } else {
                info!(
                    config = %cli_config.path.display(),
                    "etcd settings not found, showing local data only"
                );
                print_host_table(&[local_state], domain_suffix);
            }
        }
        None => {
            info!("config not found, showing local data only");
            print_host_table(&[local_state], domain_suffix);
        }
    }

    Ok(())
}
