[package]
name = "ogygia-irisd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# CLI and config
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
hostname = { workspace = true }
strum = { workspace = true }

# HTTP server
axum = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }

# HTTP client
reqwest = { workspace = true }

# Bloom filters
fastbloom = { workspace = true }
arc-swap = { workspace = true }

# Randomization
rand = { workspace = true }

# Cryptography and hashing
base64 = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
siphasher = { workspace = true }

# Cache
moka = { workspace = true }

# Compression
async-compression = { workspace = true }

# Serialization
bincode = { workspace = true }
serde_json = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Utilities
bytes = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }

# Filesystem watching
notify = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
