//! Ogygia - Fleet-wide NixOS build revision status viewer.
//!
//! Ogygia is a read-only CLI tool for viewing NixOS system build revisions
//! across a fleet of hosts. It can operate in local-only mode (reading from
//! the local filesystem) or fleet mode (fetching data from etcd).
//!
//! # Usage
//!
//! ```bash
//! # View status (local only if etcd not configured)
//! ogygia status
//!
//! # Override configuration file location
//! OGYGIA_CONFIG=/path/to/config.toml ogygia status
//!
//! # Override hostname detection
//! OGYGIA_HOSTNAME=myhost.example.com ogygia status
//!
//! # Push store paths to irisd (requires irisd feature)
//! nix build ... --print-out-paths | ogygia iris push --signing-key ./my-key
//! ```
//!
//! # Configuration
//!
//! Configuration is typically generated by the NixOS module at build time
//! and stored in the system closure. See the `status` module for details.

#[cfg(feature = "irisd")]
mod iris;
#[cfg(feature = "nebula")]
mod nebula;
mod status;

use std::process;

use anyhow::Result;
use clap::Parser;
use clap::Subcommand;
use tracing::error;
use tracing_subscriber::EnvFilter;

/// Ogygia CLI application.
#[derive(Parser)]
#[command(name = "ogygia", version, about = "ogygia")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Show build commits for the local host and etcd fleet
    Status,
    /// Interact with irisd binary cache
    #[cfg(feature = "irisd")]
    Iris(iris::IrisArgs),
    /// Manage Nebula CA, host keys, and certificates
    #[cfg(feature = "nebula")]
    Nebula(nebula::NebulaArgs),
}

impl Command {
    fn run(&self) -> Result<()> {
        match self {
            Command::Status => status::show_status(),
            #[cfg(feature = "irisd")]
            Command::Iris(args) => args.run(),
            #[cfg(feature = "nebula")]
            Command::Nebula(args) => args.run(),
        }
    }
}

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| EnvFilter::new("ogygia=info,warn")),
        )
        .with_writer(std::io::stderr)
        .init();

    let cli = Cli::parse();
    if let Err(error) = cli.command.run() {
        error!(%error, "fatal error");
        process::exit(1);
    }
}
