//! Ogygia - Fleet-wide NixOS build revision status viewer.
//!
//! Ogygia is a read-only CLI tool for viewing NixOS system build revisions
//! across a fleet of hosts. It can operate in local-only mode (reading from
//! the local filesystem) or fleet mode (fetching data from ZooKeeper).
//!
//! # Usage
//!
//! ```bash
//! # View status (local only if ZooKeeper not configured)
//! ogygia status
//!
//! # Override configuration file location
//! OGYGIA_CONFIG=/path/to/config.toml ogygia status
//!
//! # Override hostname detection
//! OGYGIA_HOSTNAME=myhost.example.com ogygia status
//! ```
//!
//! # Configuration
//!
//! Configuration is typically generated by the NixOS module at build time
//! and stored in the system closure. See the `status` module for details.

mod status;

use clap::Parser;
use std::process;

/// Ogygia CLI application.
#[derive(Parser)]
#[command(name = "ogygia", version, about = "ogygia")]
struct Cli {
    #[command(subcommand)]
    command: status::Command,
}

fn main() {
    let cli = Cli::parse();
    if let Err(error) = cli.command.run() {
        eprintln!("error: {error}");
        process::exit(1);
    }
}
